In [6]:
import math
alpha = -math.inf
beta = math.inf

# TODOS heuristic
# eliminate based on k
# state object


#1 - we want state to be a string
#2 - k to be passed thru the function
#3 - if visited dont visit again

# visited values :  a dict with keys as the state and values as the heuristic value
# set of visited nodes to check if the 
def Maximize(state,k):
    if state in visited_nodes:
        # return visited_values[state]
    if k == 0 or terminal_test(state) :
        return None,heuristic(state)
    max_child,max_utility = None, -math.inf
    for child in state.children:
        _,utility , k = Minimize(child,k)
        # add to visited node
        if utility > max_utility :
            max_child , max_utility = child , utility
            # state : max_utility to visited values
    k-=1
    return max_child , max_utility , k


def Minimize(state,k):
    if k == 0 or terminal_test(state):
        return None,heuristic(state)

    min_child,min_utility = None, math.inf
    for child in state.children:
        _,utility , k = Maximize(child,k)
        if utility < min_utility :
            min_child , min_utility = child , utility
    k-=1
    return min_child , min_utility , k

def Maximize_alpha_beta(state,alpha=-math.inf,beta=math.inf,k=0):
    if k == 0 or terminal_test(state):
        return None,heuristic(state)
    max_child,max_utility = None, -math.inf
    for child in state.children:
        _ , utility , alpha , beta , k = Minimize_alpha_beta(child,alpha,beta,k)
        if utility > max_utility :
            max_child , max_utility = child , utility
        if max_utility >= beta:
            break
        if max_utility > alpha: 
            alpha = max_utility
    k-=1
    return max_child , max_utility , alpha , beta , k

def Minimize_alpha_beta(state,alpha=-math.inf,beta=math.inf,k=0):
    if k == 0 or terminal_test(state):
        return None,heuristic(state)
    min_child,min_utility = None, math.inf
    for child in state.children:
        _, utility , alpha , beta , k = Maximize_alpha_beta(child,alpha,beta,k)
        if utility < min_utility :
            min_child , min_utility = child , utility
        if min_utility <= alpha:
            break
        if min_utility < beta: 
            beta = min_utility
    k-=1
    return min_child , min_utility , alpha , beta , k

def terminal_test(state):
    # check for winning only
    pass
def heuristic(state):
    # returns an int, +ve points for max , -ve points for min
    pass

In [4]:
def func(x):
    x = list(x)
    x[0] = "X"
    x = str(x)
x = "xYZ"
x = func(x)
print(x)

xYZ


In [3]:
import numpy as np
import sys
import time
import random


DIMENSIONS = (4,4)
MAX_DEPTH = 5

class State:
    def __init__(self):
        self.board = np.zeros((DIMENSIONS[0],DIMENSIONS[1]), dtype=int)
        self.children = []
        self.parent = None
        self.level = 0
    
    def __str__(self):
        return str(self.board)
    
    def setParent(self,parent):
        self.parent = parent
        self.parent.children.append(self)
        self.level = self.parent.level + 1

In [4]:
s= State()
s.__str__()

'[[0 0 0 0]\n [0 0 0 0]\n [0 0 0 0]\n [0 0 0 0]]'

In [5]:
import numpy as np
import sys
import time
import random

# DIMENSIONS = (6,7)
DIMENSIONS = (4,4)
MAX_DEPTH = 5

class State:
    def __init__(self,board=None):
        if board:
            self.board = board
        else :
            self.board = np.zeros((DIMENSIONS[0],DIMENSIONS[1]), dtype=int)
        self.children = []
        self.parent = None
        self.level = 0
    
    def __str__(self):
        return str(self.board)
    
    def setParent(self,parent):
        self.parent = parent
        self.parent.children.append(self)
        self.level = self.parent.level + 1

In [24]:
def decision(state,verbose=False):
    # Resetting the state each decision
    state_reset = State()
    state_reset.board = np.copy(state.board)
    visited = dict({})
    child,_ = maximize(state_reset,visited)
    return child

def generate_children(state,player,verbose=False):
    for j in range(DIMENSIONS[1]):
        for i in range(DIMENSIONS[0]-1 , -1, -1):
            if state.board[i][j] == 0:
                child = State()
                child.board = np.copy(state.board)
                child.board[i][j] = player
                child.setParent(state)
                if verbose:
                    print(child)
                    print()
                    # time.sleep(0.5)
                break

# dict yekoon el el key beta3o state.__str__ we awel mate7seblo el minimax value beta3 el state
def maximize(state,visited):
    
    visited_nodes = set(visited.keys())
    state_str = state.__str__()
    if state_str in visited_nodes:
        return None,visited[state_str]

    # either the board is full or the level == k
    if is_terminal(state):
        hn = heuristic(state)
        visited[state_str] = hn
        return None, hn
    
    max_child = None
    max_utility = -sys.maxsize
    
    generate_children(state,1)

    # han add fen we ne update el weights fen??
    for child in state.children:
        _, utility = minimize(child,visited)
        if utility > max_utility:
            max_child = child
            max_utility = utility
    
    visited[state.__str__()] = max_utility
    # 3awzeen max depth+el string el benecreate minno el states tet7at fel header beta3 el function 3ashan hana5odha min el gui
    return max_child, max_utility

            
def minimize(state,visited):
    visited_nodes = set(visited.keys())
    state_str = state.__str__()
    if state_str in visited_nodes:
        return None,visited[state_str]

    # either the board is full or the level == k
    if is_terminal(state):
        hn = heuristic(state)
        visited[state_str] = hn
        return None, hn

    min_child = None
    min_utility = sys.maxsize
    generate_children(state,2)

    for child in state.children:
        _, utility = maximize(child,visited)
        if utility < min_utility:
            min_child = child
            min_utility = utility

    visited[state.__str__()] = min_utility
    return min_child, min_utility

def is_terminal(state):
    # further improvement check the first row only for complexity --- we momkin da bardo
    # 0 not in de momkin ne8ayarha be enina ne3mil counter lil peices 3ashan el check haye7sal keteer
    if state.level == (6*7) or state.level >= MAX_DEPTH:
        return True
    return False

def heuristic(state):
    # basic heuristic for now 
    if who_win(state) == 1:
        return 1000
    elif who_win(state) == 2:
        return -1000
    return random.randint(-100,100)


# momkin ne7tag-ha fe 7esabet el scores
# + check 3ala el diagonal el 3aksy

def who_win(state):
    '''
    Returns 1 if player 1 wins, 2 if player 2 wins, 0 if no one wins
    '''
    # Check horizontal
    for i in range(DIMENSIONS[0]):
        for j in range(DIMENSIONS[1]-3):
            condition_win = state.board[i][j] == state.board[i][j+1] == state.board[i][j+2] == state.board[i][j+3] == 1
            condition_lose = state.board[i][j] == state.board[i][j+1] == state.board[i][j+2] == state.board[i][j+3] == 2

            if condition_win:
                return 1
            elif condition_lose:
                return 2
            
    # Check vertical
    for i in range(DIMENSIONS[0]-3):
        for j in range(DIMENSIONS[1]):
            condition_win = state.board[i][j] == state.board[i+1][j] == state.board[i+2][j] == state.board[i+3][j] == 1
            condition_lose = state.board[i][j] == state.board[i+1][j] == state.board[i+2][j] == state.board[i+3][j] == 2

            if condition_win:
                return 1
            elif condition_lose:
                return 2
            
    # Check diagonal
    for i in range(DIMENSIONS[0]-3):
        for j in range(DIMENSIONS[1]-3):
            condition_win = state.board[i][j] == state.board[i+1][j+1] == state.board[i+2][j+2] == state.board[i+3][j+3] == 1
            condition_lose = state.board[i][j] == state.board[i+1][j+1] == state.board[i+2][j+2] == state.board[i+3][j+3] == 2
            if condition_win:
                return 1
            elif condition_lose:
                return 2
            
    # Check anti-diagonal
    for i in range(DIMENSIONS[0]-3):
        for j in range(3, DIMENSIONS[1]):
            condition_win = state.board[i][j] == state.board[i+1][j-1] == state.board[i+2][j-2] == state.board[i+3][j-3] == 1
            condition_lose = state.board[i][j] == state.board[i+1][j-1] == state.board[i+2][j-2] == state.board[i+3][j-3] == 2
            
            if condition_win:
                return 1
            elif condition_lose:
                return 2
    
    return 0

# def input_array():
#     array_4x4 = []
#     for i in range(4):
#         row = input(f"Enter 4 elements for row {i + 1} separated by spaces: ").split()
        
#         # Check if the user entered exactly 4 elements
#         if len(row) != 4:
#             print("Please enter exactly 4 elements for each row.")
#             break
        
#         # Convert input elements to integers and append to the array
#         row = [int(element) for element in row]
#         array_4x4.append(row)
    
#     array = np.array(array_4x4)

#     return array

def input_array():
    array_4x4 = []
    for i in range(4):
        row = input(f"Enter 4 elements for row {i + 1} separated by spaces: ").split()
        
        # Check if the user entered exactly 4 elements
        if len(row) != 4:
            print("Please enter exactly 4 elements for each row.")
            break
        
        # Convert input elements to integers and append to the array
        row = [int(element) for element in row]
        array_4x4.append(row)
    
    array = np.array(array_4x4)

    return array

state = State()
while(1):
    child = decision(state,verbose=False)
    if child is None:
        print("Game end")
        exit()
    print(child)
    print()

    array = input_array()
    
    print()
    time.sleep(0.25)
    state.board = np.copy(array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]



Enter 4 elements for row 1 separated by spaces:  0 0 0 0 
Enter 4 elements for row 2 separated by spaces:  0 0 0 0 
Enter 4 elements for row 3 separated by spaces:  0 0 0 0 
Enter 4 elements for row 4 separated by spaces:  0 2 0 0



[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 2 0 0]]



KeyboardInterrupt: Interrupted by user

In [33]:
l = [1,2,3,4]
def k(l):
    print(l[2] == 3)
k(l)
print(l)

True
[1, 2, 3, 4]


In [37]:
l.deque(0)

AttributeError: 'list' object has no attribute 'deque'

In [48]:
import random 
np.arange(5, 8)

array([5, 6, 7])

In [67]:
np.random.choice(np.arange(5, 8), p=[0.2,0.6,0.2])

7

In [74]:
l = [1,2,3,4]

In [75]:
l.index(4)

3

In [79]:
from treelib import Node, Tree
tree = Tree()

tree.create_node("Harry", "harry")  # No parent means its the root node
tree.create_node("Jane",  "jane"   , parent="harry")
tree.create_node("Bill",  "bill"   , parent="harry")
tree.create_node("Diane", "diane"  , parent="jane")
tree.create_node("Mary",  "mary"   , parent="diane")
tree.create_node("Mark",  "mark"   , parent="jane")
tree.show()


b'Harry\n\xe2\x94\x9c\xe2\x94\x80\xe2\x94\x80 Bill\n\xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 Jane\n    \xe2\x94\x9c\xe2\x94\x80\xe2\x94\x80 Diane\n    \xe2\x94\x82   \xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 Mary\n    \xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 Mark\n'


zsh:1: command not found: pip


In [101]:
cols = 7
rows = 6
player_val=1
ai_val=2
def check_winner(board):
    global player_val,ai_val

    ai_count = 0
    p_count = 0
    moves =[[1,0],[0,1],[1,1],[1,-1]] #[col,row] 1. checks horizontal 2. vertical  3. diagonal +ve  4. diagonal -ve
    for m in moves:
        col_move = m[0]
        row_move = m[1]
        for c in range(cols):
            for r in range(rows):
                max_c = c + 3*col_move
                max_r = r + 3*row_move
                if (0 <= max_c and max_c < cols and 0 <= max_r and max_r < rows):
                    if(board[r][c] != 0):
                        winner = board[r][c]
                        if((board[r+row_move][c+col_move] == winner) and (board[r+2*row_move][c+2*col_move] == winner) and (board[r+3*row_move][c+3*col_move] == winner)):
                            if winner == player_val:
                                p_count+=1
                            else:
                                ai_count +=1

    print(p_count,ai_count)
    if (p_count> ai_count):
        return player_val
    return ai_val

In [102]:
board = [[2 ,1, 1, 2, 1, 1, 1],[2, 2, 2, 2, 2, 1, 1],[2, 1, 1, 2, 2, 1, 2],[2, 2, 2, 2, 2, 1, 1],[2, 2, 1, 1, 1, 2, 1],[2, 1, 1, 1, 2, 1, 1]]

In [103]:
check_winner(board)

1 11


2

In [107]:
str(None)

'None'